# -*- coding: utf-8 -*-
"""tourism_app(streamlit).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExRJNYgcq5HggChZE5rKLORpDyv8aoCh
"""

!pip install streamlit
!pip install plotly
!pip install folium
!pip install streamlit-folium
!pip install geopandas
!pip install geopy

import streamlit as st
import pandas as pd
import plotly.express as px
import folium
from streamlit_folium import st_folium

# ----------------- Streamlit App ------------------
st.set_page_config(page_title="Incredible India Explorer", layout="wide")

st.title("\U0001F30D Incredible India Explorer")
st.markdown("""
Welcome to the cultural heart of India! This platform helps you:
- Discover **traditional Indian art forms**
- Explore **cultural hotspots**
- Learn about **government support** for art and tourism
- Promote **responsible tourism**
""")

# ----------------- Sidebar Filters ------------------
st.sidebar.title("Filters")
selected_state = st.sidebar.selectbox("Select a State", ["All", "Rajasthan", "Kerala", "West Bengal", "Tamil Nadu"])
selected_art = st.sidebar.selectbox("Select Art Form", ["All", "Kathakali", "Madhubani", "Warli", "Chhau"])

# ----------------- Art & Culture Explorer ------------------
st.subheader("\U0001F3A8 Art & Culture Explorer")

# ----------------- Art & Culture Explorer ------------------
st.subheader("\U0001F3A8 Art & Culture Explorer")
art_data = pd.read_csv("art_forms.csv")
if selected_state != "All":
    art_data = art_data[art_data['State'] == selected_state]
if selected_art != "All":
    art_data = art_data[art_data['ArtForm'] == selected_art]

for _, row in art_data.iterrows():
    with st.expander(f"{row['ArtForm']} - {row['State']}"):
        st.image(row['ImageURL'], width=300)
        st.write(row['Description'])

# ----------------- Cultural Hotspot Dashboard ------------------
st.subheader("\U0001F5FA Cultural Hotspot Dashboard")
tourism_df = pd.read_csv("tourism_trends.csv")
fig = px.line(tourism_df, x='Year', y='TouristCount', color='Region', title='Annual Tourism Trends by Region')
st.plotly_chart(fig, use_container_width=True)

# Monthly seasonality chart
st.write("### Monthly Tourist Seasonality")
monthly_df = pd.read_csv("monthly_seasonality.csv")
fig2 = px.bar(monthly_df, x='Month', y='TouristCount', color='Region', barmode='group',
              title='Monthly Tourist Trends Across Regions')
st.plotly_chart(fig2, use_container_width=True)

# Map
st.write("### Cultural Hotspot Map")
map_df = pd.read_csv("hotspot_locations.csv")
m = folium.Map(location=[22.5937, 78.9629], zoom_start=5)
for _, row in map_df.iterrows():
    folium.Marker(
        [row['Latitude'], row['Longitude']],
        popup=f"{row['Place']} ({row['State']})",
        tooltip=row['Place']
    ).add_to(m)
st_folium(m, width=700)

# ----------------- Hidden Cultural Gems ------------------
st.subheader("\U0001F3F0 Hidden Cultural Gems")
hidden_gems = pd.read_csv("hidden_gems.csv")
for _, row in hidden_gems.iterrows():
    with st.expander(f"{row['Place']} - {row['State']}"):
        st.image(row['ImageURL'], width=300)
        st.markdown(f"**Why it's unique:** {row['Description']}")
        st.markdown(f"**Challenges:** {row['Challenges']}")
        st.markdown(f"**Why it's under-visited:** {row['UntouchedReason']}")

# ----------------- Government Schemes & Support ------------------
st.subheader("\U0001F4CA Government Schemes & Support")
gov_data = pd.read_csv("government_schemes.csv")
st.dataframe(gov_data)

# ----------------- Promote Responsible Tourism ------------------
st.subheader("\U0001F4AA Promote Responsible Tourism")
st.markdown("""
- Support local artisans and craftsmen
- Participate in cultural workshops
- Follow eco-friendly travel practices
- Spread awareness and educate others
""")

# ----------------- Data Source Info ------------------
st.markdown("""
### ℹ️ Data Source Information
All datasets have been curated from official resources like [data.gov.in](https://data.gov.in), Ministry of Tourism, and the Archaeological Survey of India.
""")

